# Generated by Django 3.2.9 on 2023-03-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pics',
        ),
    ]
